### ISSUE TITLE
Rubygems

### ISSUE THREAD

**Issue by dgilperez** [avit/schedule_attributes#10]
Hi! 

Are you considering publishing this fork to rubygems? It seems to be the one that is actively maintained, versus the original fork ... isn't it?

Thanks for sharing!

**Comment by avit** [comment]
Yes, I plan to. I need to update the README but I will put it up there soon.

**Comment by dgilperez** [comment]
Great! Thanks for replying! You've got a new watcher :)

**Comment by avit** [comment]
Closing old tickets. This is available on rubygems.
