### ISSUE TITLE
Form usage example

### ISSUE THREAD

**Issue by dgilperez** [avit/schedule_attributes#11]
Hi! 

I'm having a bad time building the form for my recurring events. May I kindly ask for an simple usage example? Is there any code you can share and add it to the README to guide the implementation? 

Many thanks for support and sorry for using the issues for asking this kind of explanations ...

Regards!

**Comment by avit** [comment]
I use this with jQuery to hide different inputs based on selections. I hope to tidy this up and publish something that can be used along with the formtastic form builder or standalone. These are the inputs you need to define:

```
# fields always visible:
repeat = (0|1)
start_time = 09:00
end_time = 17:00

# fields visible for non-repeating schedules (builder.one_time_fields)
# (+ button to add single dates)
dates[] = 2013-03-08, [...]

# fields visible for repeating schedules (builder.repeat_fields)
start_date = 2013-03-08
end_date = 2013-06-08
interval = 1 # every N
interval_unit = (day|week|month|year)

# fields visible for repeating day/week schedules(builder.ordinal_fields)
ordinal_unit = (day|week) # uncheck all weekdays if "day" gets selected 
ordinal_day = 1..31 # visible for ordinal_unit = day
ordinal_week = (1|2|3|4|-1) # visible for ordinal_unit = week

# checkbox fields visible for ordinal_unit = week  (builder.weekday_fields)
# (Setting all off or all on converts a "weekly" to a "daily")
monday = (0|1)
tuesday = (0|1)
wednesday = (0|1)
thursday = (0|1)
friday = (0|1)
saturday = (0|1)

# optional inputs for limiting to seasonal ranges
yearly_start_day
yearly_start_month
yearly_end_day
yearly_end_month
```

Hope this helps for now...

**Comment by dgilperez** [comment]
Yeah thanks a lot !!! I realized that the form helper will work only along with `Formtastic` so I'm building my own. 

Again, thanks for sharing!

**Comment by dgilperez** [comment]
Hi again! 

I'm trying to implement the FormBuilder as per `ActionView::Helpers`, with the idea of contributing for others to use, and I'm having little success. I wonder if you could have a look at the code here: https://github.com/dgilperez/schedule_attributes

I'm calling the included methods like this:

```
= form_for assignment do |f|
  = f.fields_for :schedule_attributes do |schedule|
    = schedule.one_time_fields
```

And the error goes: 

```
undefined method `repeat' for "assignment[schedule_attributes]":String
```

Any idea?
Thanks !!!
