### ISSUE TITLE
schedule_attributes method missing 

### ISSUE THREAD

**Issue by dgilperez** [avit/schedule_attributes#12]
Hi! 

I'm not able to access the `schedule_attributes` method for my scheduled model. I just added the gem to the Gemfile, included the module to my model and added the `:schedule_yaml` field to the DB. 

```
class Assignment < ActiveRecord::Base
  include ScheduleAttributes
end
```

And the output on the Rails console: 

```
1.9.3p327 :008 > Assignment.last.schedule_attributes
  Assignment Load (0.2ms)  SELECT `assignments`.* FROM `assignments` ORDER BY `assignments`.`id` DESC LIMIT 1
NoMethodError: undefined method `schedule_attributes' for #<Assignment:0x0000012fc025a8>
```

Any ideas?

Best regards!

**Comment by avit** [comment]
It goes like this, in order to define the column name (defaults to "schedule"):

```
class Assignment < ActiveRecord::Base
  has_schedule_attributes :column_name => 'schedule'
end
```

**Comment by dgilperez** [comment]
Thanks for answering ! I realized it already looking at the code ... and just after having it working I read this issue https://github.com/avit/schedule_attributes/issues/5 ... 

Yes, it'd be great if you update the README :)
